export type FieldTypes = Record<MetaobjectField, string>;

export type MetaobjectField =
  | 'boolean'
  | 'color'
  | 'date'
  | 'date_time'
  | 'dimension'
  | 'json'
  | 'money'
  | 'multi_line_text_field'
  | 'number_decimal'
  | 'number_integer'
  | 'rating'
  | 'rich_text_field'
  | 'single_line_text_field'
  | 'url'
  | 'volume'
  | 'weight'
  | 'collection_reference'
  | 'file_reference'
  | 'metaobject_reference'
  | 'mixed_reference'
  | 'page_reference'
  | 'product_reference'
  | 'variant_reference';
